### ISSUE TITLE
I mobilvisning dækker search over layertoggle

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#10]
I mobilvisning dækker search over layertoggle.

![image](https://user-images.githubusercontent.com/28621416/138064542-9017513f-88f4-48a6-afd2-da751fdec408.png)

Genskab fejlen ved at lave en widget med begge controls og simulér en smartphone-visning. Mit forslag til løsning er at layertoogle flyttes ned i niveau med zoom ind og ud.

**Comment by karstenpihl** [comment]
Løsningen er at tilføje følgende CSS på de widgets, hvor der både er "layertoggle" og "search" på og "layertoggle" samtidig er placeret i øverste højre hjørne:

```css
@media (max-width: 460px) {
  .widget-layertoggle.widget-control-position-ur {
    top: 51px !important;
  }
}
```

"layertoggle" funktionen ved ikke at "search" funktionen er på og kan derfor desværre ikke selv kompensere for det.
